# Set defaults
- defaults:
   link:
      create: true      # Create parent directory if necessary
      relink: true      # Overwrite incorrect symbolic links

# Clean dead symbolic links in ~/
- clean: ['~']

# Execute shell commands
- shell:
   - [git submodule update --init --recursive, Installing submodules]

# Link files from this directory
- link:
    ~/.vimrc:
    ~/.vim:
    ~/.bashrc: 
    ~/.bashrc.user:
    ~/.cshrc: 
    ~/.cshrc.user:
    ~/.dircolors:
    #~/.dircolors: misc/dircolors-solarized/dircolors.ansi-dark
    ~/.bash_profile:


